# Generated by Django 6.0.7 on 2026-07-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_complaint_feedback_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upvote',
            name='citizen',
        ),
        migrations.RemoveField(
            model_name='upvote',
            name='complaint',
        ),
        migrations.RenameField(
            model_name='complaint',
            old_name='category',
            new_name='department',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Upvote',
        ),
    ]
